/*
ProjectEuler.net
Problem 2 - Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
 */
public class Problem002 {
    public static void main(String[] args) {
        long fib1 = 1;
        long fib2 = 2;
        long fibSum = 1;
        long sumOfEvenTerms = 0;

        while (fibSum < 4_000_000) {
            fibSum = fib1 + fib2;
            if ((fib2 % 2) == 0) {
                sumOfEvenTerms += fib2;
            } // if
            fib1 = fib2;
            fib2 = fibSum;
        } // while

        System.out.println( "answer is " + sumOfEvenTerms);

    } // main()
} // class Problem002
